name: Python Lint, Radon, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 pyflakes pylint radon pytest

    - name: Run AutoPep8
      run: autopep8 --diff --exit-code hw2_debugging.py rand.py

    - name: Run Pyflakes
      run: pyflakes hw2_debugging.py rand.py

    - name: Run Pylint
      run: pylint hw2_debugging.py rand.py

    - name: Run Radon Cyclomatic Complexity
      run: radon cc hw2_debugging.py rand.py -a

    - name: Run Radon Maintainability Index
      run: radon mi hw2_debugging.py rand.py

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Pytest
      run: pytest test_hw2_debugging.py